### ISSUE TITLE
2 players in one page fail

### ISSUE THREAD

**Issue by racci** [ampervue/ngJWPlayer#1]
I could not use 2 jwplayers in one page.
2nd one overwrite first one.
only second one plays.

**Comment by dkarchmer** [comment]
Yes, I am afraid that is a current limitation (need to describe it on the readme). The limitation is probably relatively easy to fix, by using a dictionary of player IDs on the service, rather than a single variable.
You are welcome to try to do this, and submit the improvement.

**Comment by dkarchmer** [comment]
Just released v0.2.0 with support for multiple players on same view. See index2.html for example

**Comment by racci** [comment]
thanks.I will check it

**Comment by racci** [comment]
It works perfect. Thanks

**Comment by racci** [comment]
Do you have any idea to use also both jwplayer6 and jwplayer7 in one project?

I include all scripts in index.html. it works fine for one of them (jwplayer6 or jwplayer7).

When I cut them from index.html and paste to player.html and want to switch from one to another using angular controller to play my video, it gives injection errors or following

"jwplayer.min.js:5 Uncaught ReferenceError: jwplayer is not defined(anonymous function) @ jwplayer.min.js:5(anonymous function) @ jwplayer.min.js:5
angular.js:12520 ReferenceError: jwplayer is not defined"

it tries to handle it in index.html 

I could not include custom jwplayer script in player.html.

I need to run some scripts when I go to player.html page.

**Comment by dkarchmer** [comment]
Sorry, using both v6 and v7 at the same time is a what I would call, a big corner case, which I wouldn't recommend doing so. I don't believe the problem is on the directive, but on the two versions conflicting with each other. Do you know if JWPlayer supports having both versions loaded at the same time? You may want to ask them. I am definitely not adding support for v6.
But you may want to migrate everything to v7, which is a much better player anyway.

**Comment by racci** [comment]
I handled using both v6 and v7 with iframe. I put each of them separately to v6.html and v7.html, and call them with iframe and it work fine while I use players options on html side in a <script> tag. it also handled 2 players in one page. 
        <script src=".../javascripts/jwplayer7.js" ></script>
        <script type="text/javascript">jwplayer.key="xxxxx"; </script>

But I want to handle players.file and option configurations on a angular controller side using your directive. I think iframe also may handle using your directive but it gives following error.

 Uncaught ReferenceError: jwplayer is not defined .................. jwplayer.js:10.

I insert scripts in v6.html and v7.html

Do you have any idea about that?
