### ISSUE TITLE
Error with Angular 1.5.8

### ISSUE THREAD

**Issue by parmarsanjay** [ampervue/ngJWPlayer#10]
I see following in my Bower.

├─┬ ng-jwplayer#0.2.2
│ └── angular#1.5.8 incompatible with ~1.4.2 (1.4.14 available, latest is 1.6.0-rc.1)

Is there a challenge running this directive with 1.5.8?

**Comment by dkarchmer** [comment]
No, it should work with 1.5.8. Need to update the dependency

**Comment by parmarsanjay** [comment]
Thanks @dkarchmer. Just tested it. I did work. I am not sure if bower is packaging 1.4.2 and 1.5.8 in my final distribution. I do have this in my bower. 

"resolutions": {
    "angular": "1.5.8",
    "angular-cookies": "1.5.8"
  }
