### ISSUE TITLE
Error injecting into controller

### ISSUE THREAD

**Issue by ykoblick** [ampervue/ngJWPlayer#11]
I seem to be getting a 'Unknown provider: jwplayerServiceProvider' when I inject the into my controller 

 function ($scope,
                $sce,
                $log,
                jwplayerService
              ) {

Everything is fine when adding to the app = angular.module('app', ['ng-jwplayer']);

Note, I am using Angular 1.5.3

**Comment by dkarchmer** [comment]
does the example work?

**Comment by ykoblick** [comment]
Maybe was a fluke - everything seems to work awesome!
