### ISSUE TITLE
Why not publish to npm repository?

### ISSUE THREAD

**Issue by w0rldart** [ampervue/ngJWPlayer#12]
Package has been published to bower, but why not to npm too?

**Comment by dkarchmer** [comment]
No real reason. Nobody has asked for it, and nobody has volunteered to do it

**Comment by w0rldart** [comment]
@dkarchmer if you create an npm account (or supply the one you have), I will add you to the owners list. https://www.npmjs.com/package/ng-jwplayer

**Comment by dkarchmer** [comment]
Thank you. My account is @dkarchmer

**Comment by w0rldart** [comment]
All sorted. You can close the ticket

**Comment by dkarchmer** [comment]
Thanks @w0rldart
