### ISSUE TITLE
How to add HD toggle

### ISSUE THREAD

**Issue by ajai-jayakumar** [ampervue/ngJWPlayer#15]
This the code you are provided as example
`$scope.file: "http://example.com/myVideo.mp4",`

How do I add multiple resolution, so that in player it displays hd toggle ?

Thanks in advance.

**Comment by dkarchmer** [comment]
You can find out how to set options directly from the jwplayer web site. Here is how to set up different resolutions. Simply add `sources` as described instead of `files`:

https://support.jwplayer.com/customer/portal/articles/1428524-hd-quality-toggling

**Comment by ajai-jayakumar** [comment]
Hi @dkarchmer ,
  As per your suggestion I have done the following steps but getting the following issue

> Index.html

`<jwplayer ng-src="{{ sources }}" player-options="options" player-id="myPlayer1"></jwplayer>`

> index.controller.js

```
$scope.name = 'JWPlayer Example';

    $scope.options = {
      type: 'mp4',
      image: 'http://example.com/myVideoPoster.jpg'
    };
$scope.sources: [{
        file: "/uploads/myVideo720.mp4",
        label: "720p HD"
      },{
        file: "/uploads/myVideo360.mp4",
        label: "360p SD",
        "default": "true"
      },{
        file: "/uploads/myVideo180.mp4",
        label: "180p Web"
      }];
```

**Output:**
`<video class="jw-video jw-reset" disableremoteplayback="" webkit-playsinline="" playsinline="" preload="auto" jw-loaded="started" src="[{"file":"/uploads/myVideo720.mp4","label":"720p HD"},{"file":"/uploads/myVideo360.mp4","label":"360p SD","default":"true"},{"file":"/uploads/myVideo180.mp4","label":"180p Web"}]"></video>`


Instead of single video src am getting entire array of object like this 

`src="[{"file":"/uploads/myVideo720.mp4","label":"720p HD"},{"file":"/uploads/myVideo360.mp4","label":"360p SD","default":"true"},{"file":"/uploads/myVideo180.mp4","label":"180p Web"}]`

How would I make sure I get resolution change option, is there any other key that I should use instead of ng-src ?

Thanks in advance.

**Comment by dkarchmer** [comment]
You should not change `$scope.sources` but add but to `$scope.options.sources`
I cannot give you support on how to use JWPlayer. Please try to get it to work with simple javascript using their examples. Once it works, you simply set $scope.options to the same object that you would have passed to `player.setup(options)` in regular javascript.
