### ISSUE TITLE
How do we create playlists?

### ISSUE THREAD

**Issue by wahiche** [ampervue/ngJWPlayer#17]
I was wondering how we would incorporate the playlist functionality of the jwPlayer.

**Comment by dkarchmer** [comment]
Check the JWPLayer documentation for the kind of options you need, and then just use those options. This is just a wrapper to the JS object

**Comment by wahiche-architech** [comment]
Thanks for getting back to me, I did eventually get it to work, now just have to figure out how to have the panel of video show instead of just a button to open the list of videos coming up.
